# Generated by Django 4.0.5 on 2022-06-29 09:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
